/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugCrashRouteImport } from './routes/debug.crash'
import { Route as AuthSuccessRouteImport } from './routes/auth/success'
import { Route as AuthCliTokenRouteImport } from './routes/auth/cli-token'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugCrashRoute = DebugCrashRouteImport.update({
  id: '/debug/crash',
  path: '/debug/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCliTokenRoute = AuthCliTokenRouteImport.update({
  id: '/auth/cli-token',
  path: '/auth/cli-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/auth/cli-token': typeof AuthCliTokenRoute
  '/auth/success': typeof AuthSuccessRoute
  '/debug/crash': typeof DebugCrashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/auth/cli-token': typeof AuthCliTokenRoute
  '/auth/success': typeof AuthSuccessRoute
  '/debug/crash': typeof DebugCrashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/auth/cli-token': typeof AuthCliTokenRoute
  '/auth/success': typeof AuthSuccessRoute
  '/debug/crash': typeof DebugCrashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-out'
    | '/auth/cli-token'
    | '/auth/success'
    | '/debug/crash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-out'
    | '/auth/cli-token'
    | '/auth/success'
    | '/debug/crash'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/settings'
    | '/sign-in'
    | '/sign-out'
    | '/auth/cli-token'
    | '/auth/success'
    | '/debug/crash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  AuthCliTokenRoute: typeof AuthCliTokenRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  DebugCrashRoute: typeof DebugCrashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/crash': {
      id: '/debug/crash'
      path: '/debug/crash'
      fullPath: '/debug/crash'
      preLoaderRoute: typeof DebugCrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cli-token': {
      id: '/auth/cli-token'
      path: '/auth/cli-token'
      fullPath: '/auth/cli-token'
      preLoaderRoute: typeof AuthCliTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  AuthCliTokenRoute: AuthCliTokenRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  DebugCrashRoute: DebugCrashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
