name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  workflow-security:
    uses: ./.github/workflows/_workflow-security.yml
    permissions:
      actions: read
      contents: read

  verify-app:
    needs: workflow-security
    if: ${{ needs.workflow-security.result == 'success' }}
    concurrency:
      group: web-main-verify-app-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/_verify-app.yml
    with:
      ref: ${{ github.sha }}

  e2e:
    needs: verify-app
    if: ${{ needs.verify-app.result == 'success' }}
    concurrency:
      group: web-main-e2e-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/_e2e.yml
    with:
      ref: ${{ github.sha }}

  deploy-app:
    needs: [workflow-security, verify-app, e2e]
    if: ${{ vars.SST_PRODUCTION_AUTO_DEPLOY_ENABLED == 'true' && needs.workflow-security.result == 'success' && needs.verify-app.result == 'success' && needs.e2e.result == 'success' }}
    concurrency:
      group: web-deploy-production
      cancel-in-progress: false
    uses: ./.github/workflows/_deploy-app.yml
    with:
      environment-name: production
      environment-url: https://${{ vars.CHILL_PRODUCTION_DOMAIN }}
      ref: ${{ github.sha }}
      sst-state-file: ${{ vars.SST_STATE_FILE_PRODUCTION }}
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      SST_STATE_AGE_IDENTITY: ${{ secrets.SST_STATE_AGE_IDENTITY }}
      SST_STATE_REPO_TOKEN: ${{ secrets.SST_STATE_REPO_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  deploy-redirects:
    needs: [workflow-security, deploy-app]
    if: ${{ always() && vars.SST_PRODUCTION_AUTO_DEPLOY_ENABLED == 'true' && needs.workflow-security.result == 'success' && needs.deploy-app.result == 'success' }}
    concurrency:
      group: web-deploy-production
      cancel-in-progress: false
    uses: ./.github/workflows/_deploy-sst-target.yml
    with:
      environment-name: production
      environment-url: https://${{ vars.BINGE_PRODUCTION_DOMAIN }}
      ref: ${{ github.sha }}
      sst-stage: production
      sst-state-file: ${{ vars.SST_STATE_FILE_PRODUCTION }}
      web-deploy-target: redirects
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      SST_STATE_AGE_IDENTITY: ${{ secrets.SST_STATE_AGE_IDENTITY }}
      SST_STATE_REPO_TOKEN: ${{ secrets.SST_STATE_REPO_TOKEN }}
