name: Verify

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: web-verify-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  workflow-security:
    uses: ./.github/workflows/_workflow-security.yml
    permissions:
      actions: read
      contents: read

  verify-app:
    uses: ./.github/workflows/_verify-app.yml

  e2e:
    needs: verify-app
    if: ${{ github.actor != 'dependabot[bot]' && needs.verify-app.result == 'success' }}
    uses: ./.github/workflows/_e2e.yml
